"""Prism database module — SQLite storage for routing, cost, and session data."""

from prism.db.database import Database
from prism.db.models import (
    ComplexityTier,
    CostEntry,
    Outcome,
    ProviderStatus,
    RoutingDecision,
    Session,
    ToolExecution,
)
from prism.db.queries import (
    cleanup_old_data,
    create_session,
    get_cost_breakdown,
    get_daily_cost,
    get_free_tier_remaining,
    get_model_success_rate,
    get_monthly_cost,
    get_routing_history,
    get_session_cost,
    increment_free_tier_usage,
    is_rate_limited,
    save_cost_entry,
    save_routing_decision,
    save_tool_execution,
    set_rate_limited,
    update_provider_status,
    update_routing_outcome,
    update_session,
)

__all__ = [
    "ComplexityTier",
    "CostEntry",
    "Database",
    "Outcome",
    "ProviderStatus",
    "RoutingDecision",
    "Session",
    "ToolExecution",
    "cleanup_old_data",
    "create_session",
    "get_cost_breakdown",
    "get_daily_cost",
    "get_free_tier_remaining",
    "get_model_success_rate",
    "get_monthly_cost",
    "get_routing_history",
    "get_session_cost",
    "increment_free_tier_usage",
    "is_rate_limited",
    "save_cost_entry",
    "save_routing_decision",
    "save_tool_execution",
    "set_rate_limited",
    "update_provider_status",
    "update_routing_outcome",
    "update_session",
]
